export const CURRENCY = [
    {label: 'AED', value: 'AED', name: 'United Arab Emirates Dirham'},
    {label: 'ALL', value: 'ALL', name: 'Albanian Lek'},
    {label: 'ARS', value: 'ARS', name: 'Argentine Peso'},
    {label: 'AUD', value: 'AUD', name: 'Australian Dollar'},
    {label: 'BND', value: 'BND', name: 'Brunei Dollar'},
    {label: 'CNY', value: 'CNY', name: 'Chinese Yuan'},
    {label: 'CZK', value: 'CZK', name: 'Czech Koruna'},
    {label: 'EUR', value: 'EUR', name: 'Euro'},
    {label: 'FJD', value: 'FJD', name: 'Fijian Dollar'},
    {label: 'GHS', value: 'GHS', name: 'Ghanaian Cedi'},
    {label: 'HTG', value: 'HTG', name: 'Haitian Gourde'},
    {label: 'JPY', value: 'JPY', name: 'Japanese Yen'},
    {label: 'KES', value: 'KES', name: 'Kenyan Shilling'},
    {label: 'KYD', value: 'KYD', name: 'Cayman Islands Dollar'},
    {label: 'MAD', value: 'MAD', name: 'Moroccan Dirham'},
    {label: 'MUR', value: 'MUR', name: 'Mauritian Rupee'},
    {label: 'NAD', value: 'NAD', name: 'Namibian Dollar'},
    {label: 'PHP', value: 'PHP', name: 'Philippine Peso'},
    {label: 'PLN', value: 'PLN', name: 'Polish Złoty'},
    {label: 'QAR', value: 'QAR', name: 'Qatari Riyal'},
    {label: 'RUB', value: 'RUB', name: 'Russian Ruble'},
    {label: 'SAR', value: 'SAR', name: 'Saudi Riyal'},
    {label: 'SSP', value: 'SSP', name: 'South Sudanese Pound'},
    {label: 'TND', value: 'TND', name: 'Tunisian Dinar'},
    {label: 'TRY', value: 'TRY', name: 'Turkish Lira'},
    {label: 'TWD', value: 'TWD', name: 'New Taiwan Dollar'},
    {label: 'USD', value: 'USD', name: 'United States Dollar'},
    {label: 'VND', value: 'VND', name: 'Vietnamese Đồng'},
    {label: 'XAF', value: 'XAF', name: 'Central African CFA Franc'},
    {label: 'XCD', value: 'XCD', name: 'East Caribbean Dollar'},
    {label: 'YER', value: 'YER', name: 'Yemeni Rial'},
    {label: 'ZMW', value: 'ZMW', name: 'Zambian Kwacha'},
    {label: 'ZWL', value: 'ZWL', name: 'Zimbabwean Dollar'},
  ];